# This workflow runs the Flake8 linter on git push

name: Flake8

on: [ push, pull_request ]

jobs:
  flake8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up Python 3.9
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v4

    - name: Install library and dependencies
      run: |
        python3 -m pip install --upgrade pip
        poetry install

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run python3 -m pflake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        poetry run python3 -m pflake8 . --count --exit-zero --statistics
