# This workflow runs the Pylint linter on git push

name: Pylint

on: [ push ]

jobs:
  pylint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4.2.0
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v4

    - name: Install library and dependencies
      run: |
        poetry run pip install --upgrade pip setuptools
        poetry install

    - name: Analysing the code with pylint
      run: |
        poetry run pylint iplib3
