# This workflow runs the Pylint linter on git push

name: Pylint

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2

    - name: Cache Poetry virtualenv
      uses: actions/cache@v1
      id: Cache
      with:
        path: ~/.virtualenvs
        key: poetry-$
        restore-keys: |
          poetry-$

    - name: Install library and dependencies
      run: |
        python -m pip install --upgrade pip
        poetry install
      if: steps.cache.outputs.cache-hit != 'true'
    
    - name: Analysing the code with pylint
      run: |
        PYTHONPATH=src/ poetry run python -m pylint .
      # find . -name '*.py' -exec pylint {} \;
